# kind 클러스터 정의. 1 control-plane + 2 worker. CNI 는 Calico 로 별도 설치 (NetworkPolicy 지원).
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cka
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
  - role: worker
  - role: worker
